version: '3'

services:
  postgres:
    image: 'postgres:9.5'
    volumes:
      - 'postgres:/var/lib/postgresql/data'

  gw2oracle:
    depends_on:
      - 'postgres'
    build: .
    expose:
      - '3000'
    env_file:
      - '.env'

  web:
    build:
      context: .
      dockerfile: config/containers/Dockerfile.nginx
    links:
      - gw2oracle
    ports:
      - '80:80'

volumes:
  postgres:
