FROM nginx
RUN apt-get update && apt-get -qq -y install apache2-utils
ENV INSTALL_PATH /gw2oracle
RUN mkdir -p $INSTALL_PATH
WORKDIR $INSTALL_PATH
RUN mkdir -p log
COPY public public/
COPY config/containers/nginx.conf /tmp/nginx.conf
RUN envsubst '$INSTALL_PATH' < /tmp/nginx.conf > /etc/nginx/conf.d/default.conf
CMD [ "nginx", "-g", "daemon off;" ]
